### ISSUE TITLE
Frontend: Installationsanleitung fehlt

### ISSUE THREAD

**Issue by HerHde** [codeforpb/trinkwasser#1]
Es Fehlen Infos, wie die [Installation](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) von `gulp`, das nachinstallieren der benötigten Module, wie `gulp-less`, `gulp-connect`, `karma`, `proxy-middleware`, die ja auch im `package.json` aufgeführt sind.
Kann man das per Bower installieren, oder wie läuft das?

**Comment by ironjan** [comment]
Habe das Projekt aktualisiert, die READMEs angepasst etc. Es sollte nun nichts außer git, einem Texteditor und einem Browser benötigt werden ;)
